#!/bin/bash

read -p "Geben sie die IP des remote PC ein:" IP_OF_REMOTE_PC;

ROS_MASTER_URI="http://${IP_OF_REMOTE_PC}$:11311"
ROS_HOSTNAME="$IP_OF_REMOTE_PC"


echo "Installation "
sudo apt-get update
sudo apt-get upgrade
wget https://raw.githubusercontent.com/ROBOTIS-GIT/robotis_tools/master/install_ros_kinetic.sh
chmod 755 ./install_ros_kinetic.sh 
bash ./install_ros_kinetic.sh

#success


echo "Install Dependent ROS Packages"
sudo apt-get install ros-kinetic-joy ros-kinetic-teleop-twist-joy \
  ros-kinetic-teleop-twist-keyboard ros-kinetic-laser-proc \
  ros-kinetic-rgbd-launch ros-kinetic-depthimage-to-laserscan \
  ros-kinetic-rosserial-arduino ros-kinetic-rosserial-python \
  ros-kinetic-rosserial-server ros-kinetic-rosserial-client \
  ros-kinetic-rosserial-msgs ros-kinetic-amcl ros-kinetic-map-server \
  ros-kinetic-move-base ros-kinetic-urdf ros-kinetic-xacro \
  ros-kinetic-compressed-image-transport ros-kinetic-rqt* \
  ros-kinetic-gmapping ros-kinetic-navigation ros-kinetic-interactive-markers

#success


echo "Install TurtleBot3 Packages"

#Install TurtleBot3 via Debian Packages.

sudo apt-get install ros-kinetic-dynamixel-sdk
sudo apt-get install ros-kinetic-turtlebot3-msgs
sudo apt-get install ros-kinetic-turtlebot3

#success


echo"Set TurtleBot3 Model Name"
echo "export TURTLEBOT3_MODEL=waffle_pi" >> ~/.bashrc

#success?



echo"Netzwerk Konfiguration"	

sed -i -e "s/^export ROS_MASTER_URI=.*/export ROS_MASTER_URI=${ROS_MASTER_URI}/g" ~/.bashrc
sed -i -e "s/^export ROS_HOSTNAME=.*/export ROS_HOSTNAME=$ROS_HOSTNAME/g" ~/.bashrc

source ~/.bashrc




